version: '3.4'

services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        - SA_PASSWORD=Testebackend2023
        - ACCEPT_EULA=Y
        - MSSQL_PID=Express
    user: root
    ports:
      - 1433:1433
    networks:
      - houseeasy_subnet
    volumes:
      - ./MSSQL_Data:/var/opt/mssql/data
  houseeasy.api:
    container_name: houseeasyapi
    image: ${DOCKER_REGISTRY-}houseeasyapi
    build:
      context: .
      dockerfile: HouseEasy.API/HouseEasy.API/Dockerfile
    depends_on:
     - sqlserver
    environment:
       - Connection_Strings__DefaultConnection=Server=sqlserver;Database=houseEasyAPI;User Id=sa;Password=Testebackend2023;
    networks:
      - houseeasy_subnet
    ports:
      - 80:80
      - 443:443

 
      
networks:
  houseeasy_subnet:
   driver: bridge